###

POST http://localhost:3000/posts/create
Content-Type: application/json

{
    "_id": 1,
    "title": "hi",
    "content": "hello",
    "sender": "test"
}

###

POST http://localhost:3000/posts/create
Content-Type: application/json

{
    "_id": 2,
    "title": "hi",
    "content": "hello",
    "sender": "test2"
}

###

GET http://localhost:3000/posts/posts

###

GET http://localhost:3000/posts/post/1

###

GET http://localhost:3000/posts/sender/test2

###

PUT  http://localhost:3000/posts/update/1
Content-Type: application/json

{
    "title": "men",
    "content": "whats up",
    "sender": "testing"
}

###

GET http://localhost:3000/posts/sender/test


###
DELETE http://localhost:3000/posts/delete/1

###

POST http://localhost:3000/posts/create
Content-Type: application/json

{
    "_id": 1,
    "title": "hi",
    "content": "hello",
    "sender": "test"
}
###

GET http://localhost:3000/posts/posts

### 

POST http://localhost:3000/comments/CreateComment
Content-Type: application/json

{
    "_id": 1,
    "postId": 1,
    "content": "ok",
    "sender": "matan"
} 
###

POST http://localhost:3000/comments/CreateComment
Content-Type: application/json

{
    "_id": 2,
    "postId": 1,
    "content": "good",
    "sender": "roni"
}

###

POST http://localhost:3000/comments/CreateComment
Content-Type: application/json

{
    "_id": 3,
    "postId": 2,
    "content": "hi",
    "sender": "eliav"
}
###

GET http://localhost:3000/posts/comments/1

###

GET http://localhost:3000/posts/comments/2

###

PUT  http://localhost:3000/comments/update/3
Content-Type: application/json

{
    "content": "whats up",
    "sender": "testing"
}
###

GET http://localhost:3000/comments/getComment/3

###

DELETE http://localhost:3000/comments/delete/3

###

GET http://localhost:3000/comments/getComment/3

